### ISSUE TITLE
Unexpected behavior when pressing back button from QR reading screen

### ISSUE THREAD

**Issue by AdriiiPRodri** [quadren/arc#1]
|Affected version|
|---|
| [PBv1.1.3](https://github.com/quadren/arc/releases/tag/PBv1.1.3) |

## Description

In the Android app I have detected a behavior that I think is not appropriate (I do not know if the same happens in IOS). 

When you press the back button to exit the QR code reading screen the app closes instead of going to the main page.

I don't know if this is a design decision, I am reporting this as I believe the user normally expects to return to the previous screen.

**Comment by quadren** [comment]
Hi @AdriiiPRodri, thank you for bringing this to our notice. This is not expected behavior, and we're working to patch it.
