### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by AISLVE** [quadren/arc#13]
Hey I was thinking if you could create a discord server and update us there specifically I know you do that on Twitter but we can have a server dedicated for just arc what do you say, I think we can also interact better there, like post issues easily, add some nice little touchups faq etc

**Comment by pixelsnis** [comment]
Hey, you can join the server here: https://discord.com/invite/BZTc4T4eev

**Comment by AISLVE** [comment]
![image](https://github.com/quadren/arc/assets/121119257/02504ea8-2cd7-4899-883e-c75c69118fc4)
