### ISSUE TITLE
Discord link expired

### ISSUE THREAD

**Issue by frieza213** [quadren/arc#14]
![image](https://github.com/quadren/arc/assets/121119257/02504ea8-2cd7-4899-883e-c75c69118fc4)

_Originally posted by @AISLVE in https://github.com/quadren/arc/issues/13#issuecomment-1951308253_

**Comment by AISLVE** [comment]
Bruv don't close issues so fastly I would have done that after reading your reply

**Comment by pixelsnis** [comment]
My bad; this link should work: [Discord](https://discord.gg/3xVkH4vpV2)
