### ISSUE TITLE
Would like to know the current status of development!

### ISSUE THREAD

**Issue by menukaonline** [quadren/arc#2]
I found this project is very interesting. But also found out that no newer version was released in months. Therefore would like to know how long it takes for us to have a stable release.

I suggest you publish a road map (or current plans) for the development in a readme.md file (if possible), so it would be helpful for people like me who are interested in having a stable version of this app.

Thank you and keep the work up!

**Comment by Rihcus** [comment]
> I found this project is very interesting. But also found out that no newer version was released in months. Therefore would like to know how long it takes for us to have a stable release.
> 
> I suggest you publish a road map (or current plans) for the development in a readme.md file (if possible), so it would be helpful for people like me who are interested in having a stable version of this app.
> 
> Thank you and keep the work up!

I agree, additionally it would be nice if the existing source code for the ios/android/mac/linux apps could be published. In particular to see how the networking protocol works. Happy 2023

**Comment by pixelsnis** [comment]
Hello! I'm the developer of Arc. I've been away from working on Arc for the last year; I've been very busy with a lot of other projects alongside college, and I've only recently got the time to pick up development again. 

I've been working on a huge overhaul of Arc for the last month, and I'm hoping to release it within the next few weeks. I'm really proud of the new update, and I can't wait for all of you to see it. 

About open-sourcing – I have been considering it, but I'd want to make sure I have a solid plan to allow open-source contributions. It's on the table, but just not confirmed at the moment. 

Just a little update from my end! Thank you for using Arc and supporting it!

**Comment by AISLVE** [comment]
@pixelsnis it's been some time when can we expect the new version now that it is delayed
